[package]
name = "aoc_2023"
version = "0.1.0"
edition = "2021"

[[bin]]
name="aoc_2023_day1"
path="src/day1.rs"

[[bin]]
name="aoc_2023_day2"
path="src/day2.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror="1.0"
regex = "1.10"
lazy_static = "1.4.0"