[package]
name = "aoc_2023_day4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_2023_shared = { path = "../shared" }
indoc = "2.0"
lazy_static = "1.4.0"
regex = "1.10"